import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <header className="p-4 bg-gray-100">
            <nav className="flex gap-4 items-center">
              <Link href="/">Home</Link>
              {/** show login/register only when not authenticated */}
              <AuthContext.Consumer>
                {(auth) => {
                  if (auth && auth.user) {
                    return (
                      <>
                        <span>Welcome, {auth.user.username}</span>
                        <button
                          className="text-blue-600"
                          onClick={() => auth.logout()}
                        >
                          Logout
                        </button>
                      </>
                    );
                  } else {
                    return (
                      <>
                        <Link href="/login">Login</Link>
                        <Link href="/register">Register</Link>
                      </>
                    );
                  }
                }}
              </AuthContext.Consumer>
            </nav>
          </header>
          <main className="p-4">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
